name: Build & Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Create .env file
        uses: SpicyPizza/create-envfile@v1.3.0
        with:
          envkey_TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          envkey_REDIRECT_URI: ${{ secrets.REDIRECT_URI }}
          envkey_CLIENT_ID: ${{ secrets.CLIENT_ID }}
          envkey_CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          directory: .

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            docker pull kuratovia/gram-work-bot-image
            docker run -d --name gram-work-bot -p 80:80 --env-file .env kuratovia/gram-work-bot-image